// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0LsjnRV4Kr6UmRCI-2E_l0wSs0SO05hY',
    appId: '1:546657970181:web:40785f91f382fc619a546c',
    messagingSenderId: '546657970181',
    projectId: 'handy-f9047',
    authDomain: 'handy-f9047.firebaseapp.com',
    storageBucket: 'handy-f9047.appspot.com',
    measurementId: 'G-LMRC48J0Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBclyiXum_wGdZdkud9DBvDsd7Wf7gIEL4',
    appId: '1:546657970181:android:b40bdaeab6783cf79a546c',
    messagingSenderId: '546657970181',
    projectId: 'handy-f9047',
    storageBucket: 'handy-f9047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzxJtzGWWPIHOZzyh_4S0YohI3F0rOIdY',
    appId: '1:546657970181:ios:2091234e98d4364f9a546c',
    messagingSenderId: '546657970181',
    projectId: 'handy-f9047',
    storageBucket: 'handy-f9047.appspot.com',
    iosBundleId: 'com.Handman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzxJtzGWWPIHOZzyh_4S0YohI3F0rOIdY',
    appId: '1:546657970181:ios:5332e570bc445e6b9a546c',
    messagingSenderId: '546657970181',
    projectId: 'handy-f9047',
    storageBucket: 'handy-f9047.appspot.com',
    iosBundleId: 'com.example.handy.RunnerTests',
  );
}
